# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gerard Llobet's Page
email: llobet@cemfi.es
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gllobet.github.io"
twitter_username: gllobet
github_username:  gllobet
locale: "en-US"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      author_profile: true

author:
  name     : "Gerard Llobet"
  avatar   : "/assets/images/llobet2020.jpg"
  bio      : "I am professor of economics at CEMFI."
  location : "Madrid, Spain"
  links:
    - label: "e-mail" 
      icon: "fas fa-envelope-square"
      url: "mailto:llobet@cemfi.es"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gllobet"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://gllobet.github.io"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://econtwitter.net/@gllobet"


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

minimal_mistakes_skin: "air"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


footer:
   links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gllobet"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://gllobet.github.io"
    - label: "Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/gllobet.bsky.social"

atom_feed:
  hide: true
